apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: kube-expose-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-expose-cr
subjects:
- kind: ServiceAccount
  name: kube-expose-sa
  namespace: kube-expose
